config/routes.rb
UnitedTweets::Application.routes.draw do
  resources :congressmembers

  get 'party/:name' => 'congressmembers#party', :as => :party

  root 'congressmembers#index'

end

app/models/congressmember.rb
class Congressmember < ActiveRecord::Base




  # :sunlight_object is a serialized data object from Sunlight's API
  def self.sunlight_data_load(sunlight_object)


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/congressmembers_controller.rb
class CongressmembersController < ApplicationController
  before_action :set_congressmember, only: [:show, :edit, :update, :destroy]

  # GET /congressmembers
  # GET /congressmembers.json
  def index
    @congressmembers = Congressmember.all
  end

  # GET /congressmembers/1
  # GET /congressmembers/1.json
  def show
  end

  def party
    @congressmembers = Congressmember.where(:party => params[:name])
    render 'index'
  end

  # GET /congressmembers/new
  def new
    @congressmember = Congressmember.new
  end

  # GET /congressmembers/1/edit
  def edit
  end

  # POST /congressmembers
  # POST /congressmembers.json
  def create
    @congressmember = Congressmember.new(congressmember_params)

    respond_to do |format|
      if @congressmember.save
        format.html { redirect_to @congressmember, notice: 'Congressmember was successfully created.' }
        format.json { render action: 'show', status: :created, location: @congressmember }
      else
        format.html { render action: 'new' }
        format.json { render json: @congressmember.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /congressmembers/1
  # PATCH/PUT /congressmembers/1.json
  def update
    respond_to do |format|
      if @congressmember.update(congressmember_params)
        format.html { redirect_to @congressmember, notice: 'Congressmember was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @congressmember.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congressmembers/1
  # DELETE /congressmembers/1.json
  def destroy
    @congressmember.destroy
    respond_to do |format|
      format.html { redirect_to congressmembers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_congressmember
      @congressmember = Congressmember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def congressmember_params
      params.require(:congressmember).permit(:first_name, :last_name, :party, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congressmembers_helper.rb
module CongressmembersHelper
end

app/views/congressmembers/_form.html.erb
<%= form_for(@congressmember) do |f| %>
  <% if @congressmember.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@congressmember.errors.count, "error") %> prohibited this congressmember from being saved:</h2>

      <ul>
      <% @congressmember.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/congressmembers/edit.html.erb
<h1>Editing congressmember</h1>

<%= render 'form' %>

<%= link_to 'Show', @congressmember %> |
<%= link_to 'Back', congressmembers_path %>

app/views/congressmembers/index.html.erb
<h1>Listing congressmembers</h1>

<table>
  <thead>
    <tr>
      <th>Mugshot</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Party</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @congressmembers.each do |congressmember| %>
      <tr>
        <td><%= link_to image_tag(congressmember.image_url), congressmember %></td>
        <td><%= congressmember.first_name %></td>
        <td><%= congressmember.last_name %></td>
        <td><%= link_to congressmember.party, party_path(name: congressmember.party) %></td>
        <td><%= congressmember.state %></td>
        <td><%= link_to 'Show', congressmember %></td>
        <td><%= link_to 'Edit', edit_congressmember_path(congressmember) %></td>
        <td><%= link_to 'Destroy', congressmember, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Congressmember', new_congressmember_path %>

app/views/congressmembers/new.html.erb
<h1>New congressmember</h1>

<%= render 'form' %>

<%= link_to 'Back', congressmembers_path %>

app/views/congressmembers/show.html.erb
<h1><%= @congressmember.first_name %> <%= @congressmember.last_name %></h1>

<p>
  <strong><%= @congressmember.party %></strong> 
  from 
  <strong><%= @congressmember.state %></strong>
</p>

<%= image_tag @congressmember.image_url %>

<div>
<%= link_to 'Edit', edit_congressmember_path(@congressmember) %> |
<%= link_to 'Back', congressmembers_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnitedTweets</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>